# NB03: Data Analysis

**LSE ME204 – Data Engineering Principles for the Social Sciences (2026)**

**LSE ID:** 250093214

## Setup

Run the cell below to ensure all required packages are installed before running all other cells.

In [2]:
!pip install python-dotenv
!pip install pyperclip
!pip install tabulate

import os
import json
import requests
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv
import pyperclip
import tabulate
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

Requirement already satisfied: python-dotenv in /opt/conda/lib/python3.13/site-packages (1.2.2)
Requirement already satisfied: pyperclip in /opt/conda/lib/python3.13/site-packages (1.11.0)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.13/site-packages (0.9.0)

## The desired graphs

Now that our dataset has been transformed, it is time to transform the raw data into graphs to answer the question of whether Pokemon has experienced power creep over the years, and if so, to what extent it has been experienced. I am going to build multiple different graphs: a line graph with the overall average BST over each of the generations; a line graph with the average BST by my three chosen categories of Pokemon (Standard, Legendary, Mythical); a histogram showing the overall distribution of BSTs, with each generation having its own bar marked by color; histograms showing the overall distribution of BSTs for my three chosen categories of Pokemon; a line graph showing the average individual base stats (hp, attack, defense, special attack, special defense, speed) by generation, each like separated by color; a segregated line graph showing the average individual base stats for my three chosen categories of Pokemon; histograms showing the overall distribution of each of the individual base stats, with each generation having its own color of bar; and histograms showing the overall distribution for each of the base stats for my three chosen categories of Pokemon, which each generation being marked by its own color of bar. 

I have chosen to use line graphs for some of my charts because I am comparing averages over a period of time (different Generations), and since line graphs are best for displaying data over time, they are my best choice here. As for why I am choosing histograms, I am using them because they display a count of all of the objects that fall into certain bins, which makes them better than bar charts for me because Pokemon BSTs and individual base stats are not always nice round numbers, so being able to group them into bins made up of round numbers will make the data cleaner.

## Creating the graphs

I am going to start by creating all of the graphs pertaining to average BSTs. Though the data has been properly transformed, I still need to create new data frames that have my values aggregated in the way that I want them to be.

### Line graph of average BST over generations

In [3]:
#First, loading the csv

df_stats = pd.read_csv('../data/processed/stats_table.csv')

df_base = pd.read_csv('../data/processed/base_table.csv')

In [4]:
dfg = (
    df_base
    .groupby(['gen_num'], as_index = False)
    ['BST'].mean()
)

dfg

  gen_num         BST
0   Gen 1  407.642384
1   Gen 2  407.180000
2   Gen 3  403.725926
3   Gen 4  445.570093
4   Gen 5  425.756410
5   Gen 6  429.305556
6   Gen 7  449.409091
7   Gen 8  439.218750
8   Gen 9  457.391667

In [5]:
avg_bst_lg = px.line(
    dfg,
    x = 'gen_num',
    y = 'BST',
    title = 'Over generations, average BSTs of all Pokemon have increased since Generation 4, though not at a consistent rate',
    subtitle = 'The BSTs were calculated by adding up all of a Pokemon\'s base stats.',
    labels = {
        'gen_num':'Generation',
        'BST':'Average Base Stat Totals'
    },
    markers = True
)

avg_bst_lg.update_yaxes(rangemode='tozero')

avg_bst_lg.show()

In [6]:
# Needs to be moved to NB02

def mon_class(row):
    if row['is_legendary'] == False and row['is_mythical'] == False:
        return 'Standard'
    elif row['is_legendary'] == True and row['is_mythical'] == False:
        return 'Legendary'
    elif row['is_legendary']== False and row['is_mythical'] == True:
        return 'Mythical'

In [7]:
df_base['Classification'] = df_base.apply(lambda row: mon_class(row), axis = 1)

df_base

,is_default,pokemon_name,pokemon_url,id,name,is_baby,is_legendary,is_mythical,forms_switchable,has_gender_differences,gen,gen_url,BST,gen_num,Classification
0,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,Standard
1,True,charmander,https://pokeapi.co/api/v2/pokemon/4/,4,charmander,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,309,Gen 1,Standard
2,True,squirtle,https://pokeapi.co/api/v2/pokemon/7/,7,squirtle,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,314,Gen 1,Standard
3,True,caterpie,https://pokeapi.co/api/v2/pokemon/10/,10,caterpie,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,195,Gen 1,Standard
4,True,weedle,https://pokeapi.co/api/v2/pokemon/13/,13,weedle,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,195,Gen 1,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,True,gholdengo,https://pokeapi.co/api/v2/pokemon/1000/,1000,gholdengo,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,550,Gen 9,Standard
1021,True,dipplin,https://pokeapi.co/api/v2/pokemon/1011/,1011,dipplin,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,485,Gen 9,Standard
1022,True,sinistcha,https://pokeapi.co/api/v2/pokemon/1013/,1013,sinistcha,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,508,Gen 9,Standard
1023,True,archaludon,https://pokeapi.co/api/v2/pokemon/1018/,1018,archaludon,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,600,Gen 9,Standard
1024,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,Standard

In [8]:
dfgc = (
    df_base
    .groupby(['Classification','gen_num'], as_index = False)
    ['BST'].mean()
)

dfgc

   Classification gen_num         BST
0       Legendary   Gen 1  605.000000
1       Legendary   Gen 2  620.000000
2       Legendary   Gen 3  620.000000
3       Legendary   Gen 4  625.555556
4       Legendary   Gen 5  613.333333
5       Legendary   Gen 6  653.333333
6       Legendary   Gen 7  540.363636
7       Legendary   Gen 8  576.818182
8       Legendary   Gen 9  571.363636
9        Mythical   Gen 1  600.000000
10       Mythical   Gen 2  600.000000
11       Mythical   Gen 3  600.000000
12       Mythical   Gen 4  600.000000
13       Mythical   Gen 5  595.000000
14       Mythical   Gen 6  600.000000
15       Mythical   Gen 7  540.000000
16       Mythical   Gen 8  600.000000
17       Mythical   Gen 9  600.000000
18       Standard   Gen 1  400.917808
19       Standard   Gen 2  393.808511
20       Standard   Gen 3  386.744000
21       Standard   Gen 4  419.849462
22       Standard   Gen 5  409.216783
23       Standard   Gen 6  411.363636
24       Standard   Gen 7  429.222222
25       Standard   Gen 8  419.285714
26       Standard   Gen 9  444.462963

In [9]:
class_bst_lg = px.line(
    dfgc,
    x = 'gen_num',
    y = 'BST',
    color = 'Classification',
    title = 'Over generations, average BSTs of Standard Pokemon have tended to increase, though not at a consistent rate',
    subtitle = 'Legendaries\' BSTs have stayed consistent until Generation 7, when they decreased. Mythicals\' BSTs have been very consistent outside of a Generation 7 dip.',
    labels = {
        'gen_num':'Generation',
        'BST':'Average Base Stat Totals'
    },
    markers = True
)

class_bst_lg.update_yaxes(rangemode='tozero')

class_bst_lg.show()

In [10]:
dfh_gen_1 = df_base[df_base['gen_num'] == 'Gen 1']
dfh_gen_2 = df_base[df_base['gen_num'] == 'Gen 2']
dfh_gen_3 = df_base[df_base['gen_num'] == 'Gen 3']
dfh_gen_4 = df_base[df_base['gen_num'] == 'Gen 4']
dfh_gen_5 = df_base[df_base['gen_num'] == 'Gen 5']
dfh_gen_6 = df_base[df_base['gen_num'] == 'Gen 6']
dfh_gen_7 = df_base[df_base['gen_num'] == 'Gen 7']
dfh_gen_8 = df_base[df_base['gen_num'] == 'Gen 8']
dfh_gen_9 = df_base[df_base['gen_num'] == 'Gen 9']

BST_hist = go.Figure()
BST_hist.add_trace(go.Histogram(
    x = dfh_gen_1['BST'],
    name = 'Gen 1',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#EE4B2B'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_2['BST'],
    name = 'Gen 2',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#EFBF04'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_3['BST'],
    name = 'Gen 3',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#00674F'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_4['BST'],
    name = 'Gen 4',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#B9F2FF'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_5['BST'],
    name = 'Gen 5',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#000000'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_6['BST'],
    name = 'Gen 6',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#305CDE'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_7['BST'],
    name = 'Gen 7',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#654321'
)
)


BST_hist.add_trace(go.Histogram(
    x = dfh_gen_8['BST'],
    name = 'Gen 8',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#898989'
)
)

BST_hist.add_trace(go.Histogram(
    x = dfh_gen_9['BST'],
    name = 'Gen 9',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#7F00FF'
)
)

BST_hist.update_layout(
    xaxis_title_text='BST', # xaxis label
    yaxis_title_text='Count of Pokemon', # yaxis label
    bargap=0.2, # gap between bars of adjacent location coordinates
    bargroupgap=0.2 # gap between bars of the same location coordinates
)

BST_hist.update_layout(
    title = go.layout.Title(
        text = 'Over time, higher BST Pokemon have become more common while lower BST Pokemon have become less common.',
        font=dict(size=11)
    )
)

BST_hist.show()

In [11]:
df_base.columns

Index(['is_default', 'pokemon_name', 'pokemon_url', 'id', 'name', 'is_baby',
       'is_legendary', 'is_mythical', 'forms_switchable',
       'has_gender_differences', 'gen', 'gen_url', 'BST', 'gen_num',
       'Classification'],
      dtype='str')

In [12]:
bst_hist = px.histogram(
    df_base,
    x = 'BST',
    color = 'gen_num',
    facet_row = 'gen_num',
    width = 700,
    height = 2000
)

bst_hist.show()

In [13]:
dfh_gen_1 = df_base[(df_base['gen_num'] == 'Gen 1') & (df_base['Classification'] == 'Standard')]
dfh_gen_2 = df_base[(df_base['gen_num'] == 'Gen 2') & (df_base['Classification'] == 'Standard')]
dfh_gen_3 = df_base[(df_base['gen_num'] == 'Gen 3') & (df_base['Classification'] == 'Standard')]
dfh_gen_4 = df_base[(df_base['gen_num'] == 'Gen 4') & (df_base['Classification'] == 'Standard')]
dfh_gen_5 = df_base[(df_base['gen_num'] == 'Gen 5') & (df_base['Classification'] == 'Standard')]
dfh_gen_6 = df_base[(df_base['gen_num'] == 'Gen 6') & (df_base['Classification'] == 'Standard')]
dfh_gen_7 = df_base[(df_base['gen_num'] == 'Gen 7') & (df_base['Classification'] == 'Standard')]
dfh_gen_8 = df_base[(df_base['gen_num'] == 'Gen 8') & (df_base['Classification'] == 'Standard')]
dfh_gen_9 = df_base[(df_base['gen_num'] == 'Gen 9') & (df_base['Classification'] == 'Standard')]

BST_hist_std = go.Figure()
BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_1['BST'],
    name = 'Gen 1',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#EE4B2B'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_2['BST'],
    name = 'Gen 2',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#EFBF04'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_3['BST'],
    name = 'Gen 3',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#00674F'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_4['BST'],
    name = 'Gen 4',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#B9F2FF'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_5['BST'],
    name = 'Gen 5',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#000000'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_6['BST'],
    name = 'Gen 6',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#305CDE'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_7['BST'],
    name = 'Gen 7',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#654321'
)
)


BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_8['BST'],
    name = 'Gen 8',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#898989'
)
)

BST_hist_std.add_trace(go.Histogram(
    x = dfh_gen_9['BST'],
    name = 'Gen 9',
    xbins = {
        'start':0,
        'end':1000,
        'size':50
    },
    marker_color = '#7F00FF'
)
)

BST_hist_std.update_layout(
    xaxis_title_text='BST', # xaxis label
    yaxis_title_text='Count of Standard Pokemon', # yaxis label
    bargap=0.2, # gap between bars of adjacent location coordinates
    bargroupgap=0.2 # gap between bars of the same location coordinates
)

BST_hist_std.update_layout(
    title = go.layout.Title(
        text = 'Standard Pokemon, overall, have become increasingly powerful over generations.',
        font=dict(size=16)
    )
)

BST_hist_std.show()

In [14]:
dfh_gen_1 = df_base[(df_base['gen_num'] == 'Gen 1') & (df_base['Classification'] == 'Legendary')]
dfh_gen_2 = df_base[(df_base['gen_num'] == 'Gen 2') & (df_base['Classification'] == 'Legendary')]
dfh_gen_3 = df_base[(df_base['gen_num'] == 'Gen 3') & (df_base['Classification'] == 'Legendary')]
dfh_gen_4 = df_base[(df_base['gen_num'] == 'Gen 4') & (df_base['Classification'] == 'Legendary')]
dfh_gen_5 = df_base[(df_base['gen_num'] == 'Gen 5') & (df_base['Classification'] == 'Legendary')]
dfh_gen_6 = df_base[(df_base['gen_num'] == 'Gen 6') & (df_base['Classification'] == 'Legendary')]
dfh_gen_7 = df_base[(df_base['gen_num'] == 'Gen 7') & (df_base['Classification'] == 'Legendary')]
dfh_gen_8 = df_base[(df_base['gen_num'] == 'Gen 8') & (df_base['Classification'] == 'Legendary')]
dfh_gen_9 = df_base[(df_base['gen_num'] == 'Gen 9') & (df_base['Classification'] == 'Legendary')]

BST_hist_leg = go.Figure()
BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_1['BST'],
    name = 'Gen 1',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#EE4B2B'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_2['BST'],
    name = 'Gen 2',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#EFBF04'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_3['BST'],
    name = 'Gen 3',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#00674F'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_4['BST'],
    name = 'Gen 4',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#B9F2FF'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_5['BST'],
    name = 'Gen 5',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#000000'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_6['BST'],
    name = 'Gen 6',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#305CDE'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_7['BST'],
    name = 'Gen 7',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#654321'
)
)


BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_8['BST'],
    name = 'Gen 8',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#898989'
)
)

BST_hist_leg.add_trace(go.Histogram(
    x = dfh_gen_9['BST'],
    name = 'Gen 9',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#7F00FF'
)
)

BST_hist_leg.update_layout(
    xaxis_title_text='BST', # xaxis label
    yaxis_title_text='Count of Legendary Pokemon', # yaxis label
    bargap=0.2, # gap between bars of adjacent location coordinates
    bargroupgap=0.2 # gap between bars of the same location coordinates
)

BST_hist_leg.update_layout(
    title = go.layout.Title(
        text = 'Increasingly more legendary Pokemon have been added over generations, each with similar power levels',
        font=dict(size=12)
    )
)

BST_hist_leg.show()

In [15]:
dfh_gen_1 = df_base[(df_base['gen_num'] == 'Gen 1') & (df_base['Classification'] == 'Mythical')]
dfh_gen_2 = df_base[(df_base['gen_num'] == 'Gen 2') & (df_base['Classification'] == 'Mythical')]
dfh_gen_3 = df_base[(df_base['gen_num'] == 'Gen 3') & (df_base['Classification'] == 'Mythical')]
dfh_gen_4 = df_base[(df_base['gen_num'] == 'Gen 4') & (df_base['Classification'] == 'Mythical')]
dfh_gen_5 = df_base[(df_base['gen_num'] == 'Gen 5') & (df_base['Classification'] == 'Mythical')]
dfh_gen_6 = df_base[(df_base['gen_num'] == 'Gen 6') & (df_base['Classification'] == 'Mythical')]
dfh_gen_7 = df_base[(df_base['gen_num'] == 'Gen 7') & (df_base['Classification'] == 'Mythical')]
dfh_gen_8 = df_base[(df_base['gen_num'] == 'Gen 8') & (df_base['Classification'] == 'Mythical')]
dfh_gen_9 = df_base[(df_base['gen_num'] == 'Gen 9') & (df_base['Classification'] == 'Mythical')]

BST_hist_myth = go.Figure()
BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_1['BST'],
    name = 'Gen 1',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#EE4B2B'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_2['BST'],
    name = 'Gen 2',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#EFBF04'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_3['BST'],
    name = 'Gen 3',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#00674F'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_4['BST'],
    name = 'Gen 4',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#B9F2FF'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_5['BST'],
    name = 'Gen 5',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#000000'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_6['BST'],
    name = 'Gen 6',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#305CDE'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_7['BST'],
    name = 'Gen 7',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#654321'
)
)


BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_8['BST'],
    name = 'Gen 8',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#898989'
)
)

BST_hist_myth.add_trace(go.Histogram(
    x = dfh_gen_9['BST'],
    name = 'Gen 9',
    xbins = {
        'start':0,
        'end':1000,
        'size':100
    },
    marker_color = '#7F00FF'
)
)

BST_hist_myth.update_layout(
    xaxis_title_text='BST', # xaxis label
    yaxis_title_text='Count of Mythical Pokemon', # yaxis label
    bargap=0.2, # gap between bars of adjacent location coordinates
    bargroupgap=0.2 # gap between bars of the same location coordinates
)

BST_hist_myth.update_layout(
    title = go.layout.Title(
        text = 'From Gen 3 to Gen 7, more mythicals per generation were added, mostly centered dfs,around 600-700 BST.',
        font=dict(size=12)
    )
)

BST_hist_myth.show()

(Write conclusions about BSTs overall)

In [19]:
dfs = (
    df_stats
    .groupby(['stat_name','gen_num'], as_index = False)
    ['base_stat'].mean()
)

dfs

          stat_name gen_num  base_stat
0            attack   Gen 1  72.913907
1            attack   Gen 2  68.260000
2            attack   Gen 3  72.537313
3            attack   Gen 4  80.038462
4            attack   Gen 5  80.306122
5            attack   Gen 6  72.696970
6            attack   Gen 7  85.602410
7            attack   Gen 8  81.617978
8            attack   Gen 9  82.456140
9           defense   Gen 1  68.225166
10          defense   Gen 2  69.690000
11          defense   Gen 3  69.149254
12          defense   Gen 4  74.346154
13          defense   Gen 5  71.265306
14          defense   Gen 6  72.803030
15          defense   Gen 7  79.433735
16          defense   Gen 8  73.112360
17          defense   Gen 9  77.245614
18               hp   Gen 1  64.211921
19               hp   Gen 2  70.980000
20               hp   Gen 3  65.783582
21               hp   Gen 4  72.230769
22               hp   Gen 5  69.394558
23               hp   Gen 6  68.484848
24               hp   Gen 7  71.554217
25               hp   Gen 8  72.235955
26               hp   Gen 9  76.561404
27   special-attack   Gen 1  67.139073
28   special-attack   Gen 2  64.500000
29   special-attack   Gen 3  67.246269
30   special-attack   Gen 4  72.711538
31   special-attack   Gen 5  67.482993
32   special-attack   Gen 6  72.696970
33   special-attack   Gen 7  76.000000
34   special-attack   Gen 8  70.179775
35   special-attack   Gen 9  72.956140
36  special-defense   Gen 1  66.086093
37  special-defense   Gen 2  72.340000
38  special-defense   Gen 3  66.589552
39  special-defense   Gen 4  73.403846
40  special-defense   Gen 5  66.299320
41  special-defense   Gen 6  73.606061
42  special-defense   Gen 7  74.662651
43  special-defense   Gen 8  69.157303
44  special-defense   Gen 9  72.447368
45            speed   Gen 1  69.066225
46            speed   Gen 2  61.410000
47            speed   Gen 3  60.955224
48            speed   Gen 4  69.307692
49            speed   Gen 5  65.136054
50            speed   Gen 6  64.075758
51            speed   Gen 7  64.481928
52            speed   Gen 8  67.651685
53            speed   Gen 9  74.991228

In [25]:
base_lg = px.line(
    dfs,
    x = 'gen_num',
    y = 'base_stat',
    facet_col = 'stat_name',
    labels = {
        'gen_num': 'Generation',
        'base_stat': 'Stat Number',
        'stat_name': 'Stat Name'
    },
    width = 2000,
    markers = True
)

base_lg.update_yaxes(rangemode='tozero')

base_lg.show()

A general increase is seen in all types of stats (except for special-defense, where we kind of wibble around a medium, but we still end Gen 9 higher than Gen 1). Still, attack has seen the highest general increase across all the stats, which is likely what is mostly driving the higher stat spreads

In [29]:
df_stats['Classification'] = df_stats.apply(lambda row: mon_class(row), axis = 1)

df_stats

,is_default,pokemon_name,pokemon_url,id_x,name,is_baby,is_legendary,is_mythical,forms_switchable,has_gender_differences,gen_x,gen_url,BST,gen_num,base_stat,stat_name,id_y,gen_y,Classification
0,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,45.0,hp,1.0,generation-i,Standard
1,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,49.0,attack,1.0,generation-i,Standard
2,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,49.0,defense,1.0,generation-i,Standard
3,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,65.0,special-attack,1.0,generation-i,Standard
4,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,65.0,special-defense,1.0,generation-i,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5960,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,80.0,attack,1019.0,generation-ix,Standard
5961,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,110.0,defense,1019.0,generation-ix,Standard
5962,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,120.0,special-attack,1019.0,generation-ix,Standard
5963,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,80.0,special-defense,1019.0,generation-ix,Standard
5964,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,44.0,speed,1019.0,generation-ix,Standard

In [31]:
dfsc = (
    df_stats
    .groupby(['stat_name','Classification','gen_num'], as_index = False)
    ['base_stat'].mean()
)

dfsc

    stat_name Classification gen_num   base_stat
0      attack      Legendary   Gen 1   96.250000
1      attack      Legendary   Gen 2   99.000000
2      attack      Legendary   Gen 3   99.375000
3      attack      Legendary   Gen 4  108.125000
4      attack      Legendary   Gen 5  118.166667
..        ...            ...     ...         ...
157     speed       Standard   Gen 5   63.143885
158     speed       Standard   Gen 6   62.967213
159     speed       Standard   Gen 7   60.671642
160     speed       Standard   Gen 8   62.253165
161     speed       Standard   Gen 9   72.411765

[162 rows x 4 columns]

In [32]:
base_lg_c = px.line(
    dfsc,
    x = 'gen_num',
    y = 'base_stat',
    color = 'Classification',
    facet_col = 'stat_name',
    labels = {
        'gen_num': 'Generation',
        'base_stat': 'Stat Number',
        'stat_name': 'Stat Name',
        'Classification': 'Pokemon Classification'
    },
    width = 2000,
    markers = True
)

base_lg_c.update_yaxes(rangemode='tozero')

base_lg_c.show()

When it comes to the standards, we do still see the general increase over time in all stats (except for, once again, special defense and speed, hp doesn't show much increase) but even though not all stats have a general upward increase, they all hover higher than Generation 1 after a certain point (most often Gens 4 and 5, except for speed when we only get more speed in Gen 9). Legendaries and Mythicals are all over the place, however, and this is likely due to the fact that they all concentrate around the same power levels (according to the histograms). Once again, at least for Standards, we do see that attack remains overall the highest stat. 

Also shows that, again, Legendaries and Mythicals are generally stronger than standards.

In [33]:
df_stats

,is_default,pokemon_name,pokemon_url,id_x,name,is_baby,is_legendary,is_mythical,forms_switchable,has_gender_differences,gen_x,gen_url,BST,gen_num,base_stat,stat_name,id_y,gen_y,Classification
0,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,45.0,hp,1.0,generation-i,Standard
1,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,49.0,attack,1.0,generation-i,Standard
2,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,49.0,defense,1.0,generation-i,Standard
3,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,65.0,special-attack,1.0,generation-i,Standard
4,True,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,1,bulbasaur,False,False,False,False,False,generation-i,https://pokeapi.co/api/v2/generation/1/,318,Gen 1,65.0,special-defense,1.0,generation-i,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5960,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,80.0,attack,1019.0,generation-ix,Standard
5961,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,110.0,defense,1019.0,generation-ix,Standard
5962,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,120.0,special-attack,1019.0,generation-ix,Standard
5963,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,80.0,special-defense,1019.0,generation-ix,Standard
5964,True,hydrapple,https://pokeapi.co/api/v2/pokemon/1019/,1019,hydrapple,False,False,False,False,False,generation-ix,https://pokeapi.co/api/v2/generation/9/,540,Gen 9,44.0,speed,1019.0,generation-ix,Standard

In [37]:

df_stats_attack = df_stats[df_stats['stat_name'] == 'attack']

stat_hst = px.histogram(
    df_stats_attack,
    x = 'base_stat',
    color = 'gen_num',
    facet_row = 'gen_num',
    width = 1000,
    height = 1000
)

stat_hst.show()